### ISSUE TITLE
Browser-sync "--single" flag no effect when opening link from email

### ISSUE THREAD

**Issue by GregVes** [GregVes/barter_JSFrontend#21]
Error message in browser:

"Loading module from “http://localhost:3000/signup/js/main.js” was blocked because of a disallowed MIME type (“text/html”)"

**Comment by oskarrough** [comment]
shouldn't the path be `/js/main.js`? — and not `/signup/js/main.js`?

**Comment by GregVes** [comment]
True, but I do not understand why it shows up this. Let's recap:
- In the email I sent, there is a "Sign up here" that has http://localhost:3000/signup/userXXX as href. 
- so when clicking, browser fetches "http://localhost:3000/signup/userXXX" (url bar) but in the error it seems that the browser instead appends "./js/main.js" (script path in index.html) to the requested address "http://localhost:3000/signup". 

I am thinking

**Comment by GregVes** [comment]
A strange behavior probably linked to the same issue. When I access manually http//XXXX**/signup** it will display the content while http//XXX/signup**/id43098** won't and will show the above error with the **/signup/js/main.js**

**Comment by oskarrough** [comment]
maybe change this 

https://github.com/GregVes/barter_JSFrontend/blob/5eb492f5d36261b6895a14ecd1e9ead078421395/src/index.html#L25

to `src="/js/main.js"`

**Comment by GregVes** [comment]
> maybe change this
> 
> https://github.com/GregVes/barter_JSFrontend/blob/5eb492f5d36261b6895a14ecd1e9ead078421395/src/index.html#L25
> 
> to `src="/js/main.js"`

Okkkk it was this! But why the hell? "./" "/" means the same, current dir, no?

**Comment by GregVes** [comment]
Now sorry, I am stupid it does mean the same!

base dir ("/") + /js/main.js != current dir (".") + /js/main.js
